= Bienvenue à l'atelier d'ingénierie de Chaos
:navtitle: Introduction
:page-layout: home
:markup-in-source: verbatim,attributes,quotes
: expérimental :


include::_attributes.adoc[]

== Explication de l ' atelier
** Résumé** :

La construction de systèmes à grande échelle et distribués change le jeu pour l'ingénierie logicielle moderne. Comment nos applications se comportent-elles face à l'échec? C'est le défi crucial que nous devons résoudre car les échecs sont inévitables.

Nous devons identifier les faiblesses de nos systèmes avant qu'ils ne se produisent dans la production.

Le but avec Chaos Engineering n'est pas de construire des outils pour arrêter les problèmes ou de trouver des vulnérabilités. Pour nous c'est de pousser vers une culture de résilience à l'imprévu.

Apportez votre ordinateur portable et rejoignez-nous pour faire votre **Expérience de Chaos** pour voir comment elle résiste aux conditions turbulentes dans la production et être préparée quand elle se produit.

Dans cet atelier pratique, les participants se familiariseront avec le concept de **Chaos Engineering** et apprendront comment le mettre en pratique en utilisant des capacités avancées de OpenShift comme OpenShift Service Mesh. En guise de décollage, les participants pourront :

* Déployer une application en utilisant **ArgoCD**
* Visualiser et surveiller un système distribué en utilisant **Openshift Service Mesh* *
* Définir et surveiller les paramètres de Chaos en utilisant **Grafana* *
* Apportez le chaos en injectant des échecs et des retards à travers **Kiali's** avancées
* Trouver et corriger les faiblesses découvertes dans les modèles modernes utilisés ici aujourd’hui

[quote, from Sidney Dekker, David Woods, and Richard Cook]
Je ne sais pas.
La résilience ne consiste pas à réduire les erreurs. Il s'agit d'améliorer les capacités positives des personnes et des organisations qui leur permettent de s'adapter efficacement et en toute sécurité sous pression.
Je ne sais pas.

== Configuration et infrastructure utilisées
L'environnement OpenShift créé pour vous est la version 4.7 de la plate-forme de conteneurs OpenShift. Ce déploiement est un environnement autonome qui fournit tout ce dont vous avez besoin pour apprendre la plateforme.
Nous utilisons sur **Openshift Cluster 4.7** fourni sur le système RHPDS dans lequel nous avons installé plusieurs opérateurs comme prérequis pour cet atelier :

* https://www.openshift.com/learn/topics/service-mesh[Openshift Service Mesh]
* https://www.openshift.com/blog/announcing-openshift-gitops[Openshift GitOps]

