= Introduction
:navtitle: Introduction

_2 MINUTE EXERCISE_

After a long and frustrated morning spending hours to solve an issue that a colleague, passing by chance with his/her 
cup of coffee, fixed in literally 5 seconds, you are finally ready to start your normal working day when ...

Your manager suddenly comes out of his/her office and walks to you with the very known face that saying *"You are in trouble!"*.
Indeed, the new release of a ***Mysterious Application*** is planned for tonight (everything is always urgent) and it seems to contain some bugs.

And of course, the developer who worked on this last release is now drinking some mojitos on the paradise island and you are the 
only one available who can save the situation. Your manager points the source code https://github.com/mcouliba/cloud-native-labs/tree/debugging[Mysterious Application^] out, 
gives you a gentle tap on the shoulder and says "Bon Courage!".

At that moment in time, you feel like you are on an island, but not the same one than your colleague.

Now you have to:

* Identify the right tools to build and run the ***Mysterious Application***
* Install them on your environment
* Build your application which could be composed by several heterogeneous languages
* Test, deploy, run it
* ...

Piouf!! Lots of things to do in a short period of time...

*"No Worry Be Happy"*, Red Hat OpenShift Container Platform, Inc is here to help!!

